language: node_js
node_js:
 - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
 - wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.0.0/browsermob-proxy-2.0.0-bin.zip
 - unzip browsermob-proxy-2.0.0-bin.zip
 - browsermob-proxy-2.0.0/bin/browsermob-proxy &
 - npm install
 - ./.travis-setup.sh
script:
 - mocha --timeout 20000 --globals Intl,IntlPolyfill,ErrorHandler test/tests.js
after_script:
  - npm run coveralls
