sudo: required
dist: trusty
language: node_js
node_js:
 - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
install:
 - wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.0.0/browsermob-proxy-2.0.0-bin.zip
 - unzip browsermob-proxy-2.0.0-bin.zip
 - browsermob-proxy-2.0.0/bin/browsermob-proxy &
 - npm install
 - echo "Install phase completed."
 - sleep 10
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 10
script:
 - echo "Running tests..."
 - mocha --timeout 20000 --globals Intl,IntlPolyfill,ErrorHandler test/tests.js
 - echo "Tests completed."
 - sleep 10
after_script:
 - echo "Running coveralls..."
 - npm run coveralls
 - sleep 10
 
